# Generated by Django 4.1.3 on 2023-01-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_job_skill_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_logo',
            field=models.FileField(blank=True, default='default_files/default_face.jpg', upload_to='account_files/profile_photos/'),
        ),
    ]
